FROM node:16-bullseye
RUN apt-get update -y
#RUN apt-get install nginx -y

RUN npm install -g tileserver-gl

RUN wget https://github.com/maptiler/tileserver-gl/releases/download/v1.3.0/test_data.zip
RUN unzip test_data.zip

CMD [ "tileserver-gl" ]
#COPY /usr/local/lib/node_modules/tileserver-gl /app

# EXPOSE 8080

#COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

# VOLUME /data
# WORKDIR /data

# CMD ["nginx", "-g", "daemon off;"]